on:
    push:
      branches: [main]
    
    pull_request:
      branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.30.2
      - name: Create coverage files
        run: deno test --allow-all --unstable --coverage=coverage # create coverage files
      - name: Create coverage report
        run: deno coverage ./coverage --lcov > coverage.lcov # create coverage report
      - name: Collect coverage
        uses: codecov/codecov-action@v3.1.1
        with:
          file: ./coverage.lcov
